# Generated by Django 2.0.3 on 2018-03-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitamin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitamin',
            name='unit',
        ),
    ]
